### ISSUE TITLE
Corrupted Content Error

### ISSUE THREAD

**Issue by urfusion** [azinkey/bootigniter#1]
Just installed the latest version from GIT. and getting Corrupted Content Error 
![screenshot_40](https://cloud.githubusercontent.com/assets/8436372/14225442/b53d0cae-f8e0-11e5-9330-343c07921c87.png)

**Comment by urfusion** [comment]
Normally this issue is due to gzip. have you used it?

**Comment by urfusion** [comment]
any update?

**Comment by azinkey** [comment]
mine recommendation to you 
1) check your url and Site Url configuration or do a fresh clone
2) check editor "Unicode" before editing-saving
3) check "Sample Hindi Content", if you see a "square box" or "bold dot" replace them with your.
